# -*- coding: utf-8 -*-
"""khatab_U_A8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SLHn8OIBSAyhZWORIk503pHFai3-cuY8

# Week 8 Assignment - Classes & Inheritance

Run the code cell below (click the play button or press **Shift+Enter**).
Answer each prompt in the box that appears. Type `no` when asked to add
another individual to finish. The program will then print every record
that was collected.
"""

# -*- coding: utf-8 -*-
"""Khatab_U_A8.ipynb

Automatically generated by Colab.

# Week 8 Assignment - Classes & Inheritance

Run the code cell below (click the play button or press **Shift+Enter**).
Answer each prompt in the box that appears. Type `no` when asked to add
another individual to finish. The program will then print every record
that was collected.
"""

# Week 8 Assignment - Classes & Inheritance
# This program builds directly on top of the Week 7 program structure.
# In Week 7 the data was stored in plain dictionaries and the validators
# were loose stand-alone functions. In this version everything is organized
# using classes, as required by the assignment:
#   - a Validator class holds every validation rule as a static method
#   - a Person base class holds the fields common to all individuals
#   - Student and Instructor inherit from Person and AUGMENT its behavior
#     by calling super() instead of replacing the parent logic
#   - finished records are stored as objects in the college_records list
#   - each object has a displayInformation method that prints itself
#
# The reusable helpers from Week 7 (get_input, ask_yes_no) are kept because
# they already do exactly what this assignment needs — they let us re-prompt
# the user on bad input without writing the same while-loop over and over.


# ---------- CONSTANTS ----------
# The forbidden character lists are defined once at the top so the rules
# are easy to find and change. This is the same approach used in Week 7.

# Characters that are NOT allowed in the name field (from the assignment)
INVALID_NAME_CHARS = ['!', '"', '@', '#', '$', '%', '^', '&', '*', '(', ')',
                      '_', '=', '+', ',', '<', '>', '/', '?', ';', ':',
                      '[', ']', '{', '}', '\\']

# Characters that are NOT allowed in the email field (from the assignment)
INVALID_EMAIL_CHARS = ['!', '"', "'", '#', '$', '%', '^', '&', '*', '(', ')',
                       '=', '+', ',', '<', '>', '/', '?', ';', ':', '[', ']',
                       '{', '}', '\\']


# ---------- VALIDATOR CLASS ----------
# The assignment requires a class called "Validator" that holds the
# validation methods. Each method takes the raw text the user typed and
# returns a tuple:
#   (is_valid, cleaned_value, error_message)
# This is the same return shape used in Week 7, which means the existing
# get_input helper can still call these methods without any changes.

class Validator:
    """Holds every validation rule used by the program."""

    # @staticmethod is used because these methods don't need access to an
    # instance — they only operate on the value passed in.

    @staticmethod
    def validate_type(value):
        """Type must be either 'student' or 'instructor' (case-insensitive)."""
        cleaned = value.lower()
        if cleaned in ("student", "instructor"):
            return True, cleaned, ""
        return False, None, "Invalid type. Please enter 'student' or 'instructor'."

    @staticmethod
    def validate_name(value):
        """Name must be primarily letters and must not contain any of the
        forbidden characters listed in the assignment."""
        # Reject anything that contains a forbidden character
        for char in value:
            if char in INVALID_NAME_CHARS:
                return False, None, f"Invalid Name. The character '{char}' is not allowed."

        # Make sure the name is "primarily" letters as the assignment requires
        letter_count = sum(1 for c in value if c.isalpha())
        if letter_count == 0:
            return False, None, "Invalid Name. The name must contain letters."
        non_space_length = len(value.replace(" ", ""))
        if non_space_length > 0 and letter_count / non_space_length < 0.7:
            return False, None, "Invalid Name. Must be primarily comprised of letters."

        return True, value, ""

    @staticmethod
    def validate_email(value):
        """Email must be primarily alphanumeric and must not contain any of
        the forbidden characters listed in the assignment."""
        # Reject anything that contains a forbidden character
        for char in value:
            if char in INVALID_EMAIL_CHARS:
                return False, None, f"Invalid Email. The character '{char}' is not allowed."

        # An email needs an @ to be structurally valid
        if "@" not in value:
            return False, None, "Invalid Email. It must contain an '@' symbol."

        # Make sure the email is "primarily" alphanumeric
        alnum_count = sum(1 for c in value if c.isalnum())
        if alnum_count / len(value) < 0.7:
            return False, None, "Invalid Email. Must be primarily alphanumeric."

        return True, value, ""

    @staticmethod
    def validate_student_id(value):
        """Student ID must be digits only and 7 characters or less."""
        if value.isdigit() and len(value) <= 7:
            return True, int(value), ""
        return False, None, "Invalid Student ID. Must be a number with 7 digits or less."

    @staticmethod
    def validate_instructor_id(value):
        """Instructor ID must be digits only and 5 characters or less."""
        if value.isdigit() and len(value) <= 5:
            return True, int(value), ""
        return False, None, "Invalid Instructor ID. Must be a number with 5 digits or less."

    @staticmethod
    def validate_required_text(value):
        """Generic non-empty text validator used for program of study,
        institution, and highest degree earned. The empty case is already
        handled by get_input, so we just accept anything that gets here."""
        return True, value, ""


# ---------- GENERIC INPUT FUNCTION ----------
# This is unchanged from Week 7. It keeps asking the user for input until
# the passed-in validator approves it, then returns the cleaned value.

def get_input(prompt, validator, required=True):
    """Prompt the user repeatedly until a valid value is entered, then return it."""
    while True:
        raw = input(prompt)

        # Handle an empty entry
        if raw == "":
            if required:
                print("This field is required. Please try again.")
                continue
            return ""  # optional field was skipped, return empty string

        # Run the field-specific validator
        is_valid, cleaned_value, error_message = validator(raw)
        if is_valid:
            return cleaned_value

        # Validation failed, show the reason and ask again
        print(error_message)


# ---------- YES / NO HELPER ----------
# Also reused from Week 7. Returns True for yes, False for no.

def ask_yes_no(prompt):
    """Ask a yes/no question and return True for yes, False for no."""
    while True:
        answer = input(prompt).lower()
        if answer in ("yes", "y"):
            return True
        if answer in ("no", "n"):
            return False
        print("Please enter yes or no.")


# ---------- PERSON CLASS (Parent / Base class) ----------
# This is the base class that Student and Instructor will inherit from.
# It only holds the fields that are common to both — name and email.

class Person:
    """Base class for any individual stored in college_records."""

    def __init__(self, name, email):
        self.name = name
        self.email = email

    def displayInformation(self):
        """Print the shared fields. The subclasses will AUGMENT this method
        by calling super().displayInformation() and then printing their own
        extra fields underneath."""
        print(f"  Name : {self.name}")
        print(f"  Email: {self.email}")


# ---------- STUDENT CLASS (inherits from Person) ----------
# A Student is a Person plus a Student ID and a program of study.

class Student(Person):
    """Represents a student. Inherits Person's name/email."""

    def __init__(self, name, email, student_id, program_of_study):
        # AUGMENTATION: call the parent's __init__ first instead of repeating
        # its assignments here, then add the Student-specific fields.
        super().__init__(name, email)
        self.student_id = student_id
        self.program_of_study = program_of_study

    def displayInformation(self):
        """Augments the parent method: prints the parent's fields first,
        then adds the Student-specific fields."""
        print("--- STUDENT RECORD ---")
        print(f"  Student ID      : {self.student_id}")
        super().displayInformation()  # reuse the parent's printing logic
        print(f"  Program of Study: {self.program_of_study}")
        print()


# ---------- INSTRUCTOR CLASS (inherits from Person) ----------
# An Instructor is a Person plus an Instructor ID, institution, and degree.

class Instructor(Person):
    """Represents an instructor. Inherits Person's name/email."""

    def __init__(self, name, email, instructor_id, institution, degree):
        # AUGMENTATION: reuse the parent's constructor for the shared fields.
        super().__init__(name, email)
        self.instructor_id = instructor_id
        self.institution = institution
        self.degree = degree

    def displayInformation(self):
        """Augments the parent method with the Instructor-specific fields."""
        print("--- INSTRUCTOR RECORD ---")
        print(f"  Instructor ID    : {self.instructor_id}")
        super().displayInformation()  # reuse the parent's printing logic
        print(f"  Last Institution : {self.institution}")
        print(f"  Highest Degree   : {self.degree}")
        print()


# ---------- GATHER ONE INDIVIDUAL ----------
# Builds a single Student or Instructor object by calling get_input for
# each field. Replaces the per-employee block from Week 7.

def get_individual():
    """Collect all fields for one individual and return the correct object."""
    # Step 1: figure out which kind of individual we're dealing with
    individual_type = get_input(
        "Is this individual a student or an instructor? ",
        Validator.validate_type,
    )

    # Step 2: collect the fields that BOTH types need
    name = get_input("Enter full name: ", Validator.validate_name)
    email = get_input("Enter email address: ", Validator.validate_email)

    # Step 3: collect the type-specific fields and return the matching object
    if individual_type == "student":
        student_id = get_input(
            "Enter Student ID (number, 7 digits or less): ",
            Validator.validate_student_id,
        )
        program = get_input(
            "Enter program of study: ",
            Validator.validate_required_text,
        )
        return Student(name, email, student_id, program)

    # Otherwise we are dealing with an instructor
    instructor_id = get_input(
        "Enter Instructor ID (number, 5 digits or less): ",
        Validator.validate_instructor_id,
    )
    institution = get_input(
        "Enter last institution graduated from: ",
        Validator.validate_required_text,
    )
    degree = get_input(
        "Enter highest degree earned: ",
        Validator.validate_required_text,
    )
    return Instructor(name, email, instructor_id, institution, degree)


# ---------- GATHER ALL INDIVIDUALS ----------
# Runs the main collection loop, adding individuals to college_records
# until the user is done. Same pattern as Week 7's gather_employees.

def gather_individuals():
    """Collect individuals one at a time until the user chooses to stop."""
    college_records = []
    while True:
        college_records.append(get_individual())
        print("Record added successfully!\n")

        if not ask_yes_no("Do you want to add another individual? (yes/no): "):
            break  # user said no, stop collecting

    return college_records


# ---------- MAIN PROGRAM ----------
# Orchestrates the whole program by calling the functions in order.

def main():
    print("=" * 55)
    print("       COLLEGE RECORDS MANAGEMENT SYSTEM")
    print("=" * 55)

    # Step 1: gather all records from the user
    college_records = gather_individuals()

    # Step 2: print every record using its own displayInformation method.
    # Each object knows how to display itself thanks to inheritance, so
    # this single loop works for both Students and Instructors.
    print("\n" + "=" * 55)
    print(f"      ALL COLLEGE RECORDS  ({len(college_records)} total)")
    print("=" * 55 + "\n")

    for record in college_records:
        record.displayInformation()


# Standard Python entry point so main() only runs when this file is executed
# directly (not when it is imported by another file).
if __name__ == "__main__":
    main()